### ISSUE TITLE
Getting TypeError

### ISSUE THREAD

**Issue by hitaya0100** [ramsy0dev/unlisted#1]
Hello! After I run the test command (unlisted dig --channel-identifier LinusTechTips --threads 7)
I get this error: TypeError: expected str, bytes or os.PathLike object, not NoneType
and traceback: 
Python311\Lib\site-packages\unlisted\cli.py:62 in dig
❱  62 │   with open(ignore_uids_from_result, "r") as result_file:
63 |              data = json.load(result_file)

Apologies as I am still a beginner at coding, but would you happen to know how to resolve this particular error?

**Comment by ramsy0dev** [comment]
Yeah i happen to ran into it too, i already fix it you can update `unlisted` with the following command to get the changes

```bash
pip install git+https://github.com/ramsy0dev/unlisted --upgrade
```
And i'm sorry for not responding soon.

Thank you

__Note__: You may run into issues with the proxies because they are scrapped as you run `unlisted` i'm working on fixing it but i's not a major issue that you will be constantly running into, if you do then please report it here or create an other issue for it.

**Comment by hitaya0100** [comment]
Thank you so so much! It works perfectly now! Have a wonderful day!
